# Generated by Django 6.0.7 on 2026-07-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospital', '0003_bed_has_guardian_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_ward',
            field=models.ForeignKey(blank=True, help_text="For Nurse accounts only: restricts this nurse's dashboard to a single ward.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nurses', to='hospital.ward'),
        ),
    ]
