# Generated by Django 6.0.7 on 2026-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='gender_restriction',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed')], default='mixed', help_text='Male-only or Female-only wards auto-assign patient gender on admission. Mixed wards (e.g. Pediatric) require manual selection.', max_length=10),
        ),
    ]
