# Generated by Django 6.0.7 on 2026-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_ward_gender_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='has_guardian_space',
            field=models.BooleanField(default=False, help_text='Bed includes a sleeper chair/pull-out bed for a parent or guardian to stay overnight (Pediatric Ward).'),
        ),
    ]
