# Generated by Django 6.0.7 on 2026-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_bed_has_guardian_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='medication_afternoon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='medication_evening',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='medication_morning',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
