# Generated by Django 6.0.7 on 2026-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_mealcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='diet',
            field=models.CharField(choices=[('standard', 'Standard Diet'), ('diabetic', 'Diabetic Diet'), ('low_salt', 'Low-Salt Diet'), ('soft', 'Soft Diet'), ('npo', 'NPO (Nil by Mouth)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
