# Generated by Django 6.0.7 on 2026-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_admission_diet_patient_patient_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_pin',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
