# Generated by Django 6.0.7 on 2026-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_patient_patient_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='medication_round_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ward',
            name='medication_round_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
